<div id="eula" class="row">
	<div class="row">
	  <div class="small-12 medium-12 large-12 columns">
	  	<h4>End User License Agreement</h4>
	  </div>
	</div>

	<div class="row">
	  <div class="small-12 medium-12 large-12 columns">

			<strong>IMPORTANT</strong>
			Please read carefully the following legally binding End Users License Agreement ("EULA") between you ("Licensee"), either an individual or a single legal entity, and Simplifie Haystack Career Services. ("Simplifie Haystack Career") for the Software defined below. By explicitly accepting this EULA, or by installing, copying, downloading, accessing, or otherwise using the Software, you acknowledge that you read, understand, and agree to be bound by the terms of this EULA. If you does not agree with the terms of this EULA, do not install or otherwise use the Software.

			Where a reseller, service provider, consultant, contractor or other party downloads or otherwise provides the Software for Licensee and / or installs or activates the Software on Licensee’s behalf prior to Licensee’s use of the Software, such reseller, service provider, consultant, contractor or other party will be deemed to be Licensee’s agent acting on Licensee’s behalf and Licensee will be deemed to have accepted all of the terms and conditions of this EULA as if Licensee had directly downloaded, installed or used the Software.

			<strong>The Website and Simplifie Haystack Platform</strong>
			Welcome to Simplifie Haystack Platform. The Simplifie Haystack Platform is owned by Simplifie Tech licensed and managed by Simplifie Haystack Career Services. ("Simplifie Haystack Career") through Simplifie Haystack Technology Ventures ("Simplifie Haystack Tech").

			Through the Services, Simplifie Haystack Career helps you in maximizing and tracking career opportunities for internships, industries, and / or employers based on your preferences; and assists you in finding opportunities that matches your listed competencies. Please remember that while use of the Services may provide assistance in your internship search and career, it is not intended to provide career, work, or human resource advice.

			The Services are made available for your personal, non-commercial use. "Personal, non-commercial use" does not include reselling or repurposing any of the elements of the Simplifie Haystack Platform or product, service, or data provided to you herein as part of your use of the Simplifie Haystack Platform and the Website. If you are unclear about whether your use is acceptable under these terms, please contact us at <?php echo site_url('main/about'); ?>.

			We are pleased to make the Services available to you, but we reserve the right to terminate or suspend the Services (or your use of the Service) at any time without notice and without liability in our sole discretion. Upon termination, you continue to be bound by this Agreement. You may use the Service to help you to manage your internship search or to find a internship, but you are solely responsible for your selection of those internships. You are also responsible for your use of the Service, and your actions in relation to those websites.

			<strong>Opening an Account</strong>
			Prior registration is not required to access the Website. However, to access certain features of the Services such as managing your internship search, sending applications through the Website, creating internship matches, alerts and notifications, etc. you will need to register online and create an Account. Through your account, you can access services and functionalities that Simplifie Haystack-Career may establish and maintain from time to time and in its sole discretion. Note that when you create an account using a company, organization, or a juridical entity’s name, then (i) "you" includes you and that entity, and (ii) you represent and warrant that you are an authorized representative of the entity with full authority to bind the Corporation or entity to this Agreement, and that you agree to this Agreement on behalf of the corporation or entity.

			You are not allowed to use someone else’s account without their permission. It is important that in creating your account that you provide accurate and complete information. You are likewise encouraged to keep your account information accurate and updated at all times to ensure maximum benefit from Simplifie Haystack’s Services. You are solely responsible for the activity that occurs on your account, including the safety and security of your password. In the event you suspect a breach of security or someone using your account without authorization, please notify Simplifie Haystack Career immediately at support@simplifie.net. Simplifie Haystack Career, or its affiliates, will not be liable for any losses caused by any unauthorized use of your account.

			You can control the data you share, the Services you subscribe too, and the level of privacy of your account by changing the settings in your Account Settings page.

			By providing your email address or opening your account with Simplifie Haystack Career, you consent to our using the email address to send you Service-related notices, including any notices required by law, in lieu of communication by postal mail. Depending on your preferences, as indicated in your profile, and any express authorization you have given, at the time you signed up for the Services, and or from time-to-time, we may also send you emails of special offers, changes to the features of our Services, and other notifications. If you do not wish to receive such email messages, you may opt out by clicking unsubscribe on the email, or changing your notification preferences in your account. Please remember, however, that opting out may prevent you from maximizing the benefits you can potentially get from use of the Service.

			<strong>Changes to the Service</strong>
			All aspects of the Service are subject to change, modification or may be discontinued at Simplifie Haystack-Career’s sole discretion. Simplifie Haystack-Career shall strive to provide notifications of any disruption of the Service, however; Simplifie Haystack-Career reserves the right to interrupt the Service with or without prior notice. You understand and agree that Simplifie Haystack-Career will not be liable to you for any interruption of the Service, delay or failure to perform.

			<strong>Your Interactions with Other Users</strong>
			You are solely responsible for your interactions with other Users. We reserve the right, but have no obligation, to monitor disputes between you and other Users including a company, organization or juridical entity’s name. Simplifie Haystack-Career shall have no liability for your interactions with other Users, or for any User’s action or inaction.

			<strong>Ownership and Reservation of Rights</strong>
			The software comprising the Website and the Simplifie Haystack Platform is owned by Simplifie Haystack Inc. and licensed in the Philippines to Simplifie Haystack-Career. The Website, including all materials, and contents therein, the Simplifie Haystack Platform, and all right, title and interest thereto are sole property of Simplifie Haystack Inc., and its licensors, and are protected by Intellectual Property laws. Except for the limited license granted to you in the EULA, Simplifie Haystack Inc., reserves for itself and its licensors all other rights, title to, and interest. Under this EULA, Simplifie Haystack, through Simplifie Haystack-Career, grants you a non-transferable, non-exclusive, non-sublicensable, royalty-free and fully paid, worldwide right and license to install or execute the Simplifie Haystack Platform, in the form made available through the Website, for your personal, non-commercial use only, subject to the terms and conditions under this EULA.

			<strong>Third-Party Materials</strong>
			This EULA does not cover any third-party materials, and all rights, tile, and interest pertaining thereto, which are the sole property of the relevant third parties and are subject to any applicable limited licenses, conditions and/or reservations.

			<strong>Indemnity</strong>
			You agree to defend, indemnify and hold harmless Simplifie Haystack, Simplifie Haystack Career, Simplifie Haystack Tech and its subsidiaries, agents, managers, and other affiliated companies, and their employees, contractors, agents, officers and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the Service, including any data or content transmitted or received by you; (ii) your violation of any term of this Agreement (iii) your violation of any third-party right, including without limitation any right of privacy, publicity rights or Intellectual Property Rights; (iv) your violation of any law, rule or regulation of the Philippines or any other country; (v) any claim or damages that arise as a result of any of your user content or any that is submitted via your account; or (vi) any other party’s access and use of the Service with your unique username, password or other appropriate security code.

			<strong>Exclusion of Warranties</strong>
			THE SERVICE IS PROVIDED ON AN "AS IS" AND "WHERE IS" BASIS WITH NO WARRANTY OF ANY KIND, WHETHER EXPRESS OR IMPLIED, REPRESENTATIONS OR ENDORSEMENTS WHATSOEVER (INCLUDING WITHOUT LIMITATION WARRANTIES OF TITLE OR NON-INFRINGEMENT, OR THE IMPLIED WARRANTIES OF MERCHANTIBILITY OR FITNESS FOR A PARTICULAR PURPOSE) WITH REGARD TO THE PRODUCT OR SERVICE, ANY MECHANDISE INFORMATION OR SERVICE PROVIDED THROUGH THE SERVICE OR ON THE INTERNET GENERALLY, AND Simplifie Haystack, Simplifie Haystack Tech, Simplifie Haystack Career, ITS AFFILIATES, DIRECTORS, EMPLOYEES OR ITS LICENSORS SHALL NOT BE LIABLE FOR ANY COST OR DAMAGE ARISING EITHER DIRECTLY OR INDIRECTLY FROM ANY SUCH USE. IT IS SOLELY YOUR RESPONSIBILITY TO EVALUATE THE ACCURACY, COMPLETENESS AND USEFULNESS OF ALL OPINIONS, ADVICE, SERVICES, MECHANDIZE AND OTHER INFORMATION PROVIDED THROUGH THE WEBSITE, THE Simplifie Haystack Platform, OR ON THE INTERNET GENERALLY. NO REPRESENTATION OR WARRANTY IS MADE HEREIN THAT THE WEBSITE OR THE SOFTWARE WILL BE UNINTERRUPTED OR ERROR-FREE OR THAT DEFECTS IN THE SERVICE WILL BE CORRECTED OR IMMEDIATELY DETECTED.

			YOU UNDERSTANT FURTHER THAT ANY CONTENT DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICE IS DOWNLOADED AT YOUR OWN RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT MAY RESULT FROM SUCH DOWNLOAD.

			Simplifie Haystack, Simplifie Haystack Tech, Simplifie Haystack Career, ITS AFFILIATES, DIRECTORS, OFFICERS, EMPLOYEES OR ITS LICENSORS DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE WEBSITE OF Simplifie Haystack Platform OR ANY HYPERLINKED WEBSITE OR SERVICE, OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND WILL NOT BE A PARTY TO OR IN ANY WAY MONITOR ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES.

			Contents, or information available through the Website or through the Simplifie Haystack Platform may contain inaccuracies or typographical errors. Simplifie Haystack, Simplifie Haystack Tech, Simplifie Haystack Career, its affiliates, directors, officers, employees or licensors hereby makes no representation or warranty about the accuracy, reliability, completeness, or timeliness of the content or about the results to be obtained from using the Services or the content on it.

			<strong>Limitation of Liability</strong>
			IN NO EVENT WILL Simplifie Haystack, Simplifie Haystack Tech, Simplifie Haystack Career, ITS AFFILIATES, DIRECTORS, OFFICERS, EMPLOYEES, OR ITS LICENSORS, OR ANY THIRD-PARTIES MENTIONED IN OUR WEBSITE OR IN THE Simplifie Haystack Platform BE LIABLE FOR (I) ANY INCIDENTAL, CONSEQUENTIAL, INDIRECT OR OTHER DAMAGES (INCLUDING BUT NOT LIMITED TO, DAMAGES FOR LOSS OF PROFITS, BUSINESS INTERRUPTION, LOSS OF PROGRAMS OR INFORMATION, AND THE LIKE) ARISING OUT OF THE USE OF OR INABILITY TO USE THE WEBSITE, OR THE Simplifie Haystack Platform, OR ANY INFORMATION, OR TRANSACTIONS PROVIDED OR DOWNLOADED FROM THE WEBSITE OR THROUGH THE Simplifie Haystack Platform, OR ANY DELAY OF SUCH INFORMATION OR SERVICE. EVEN IF OUR WEBSITE OR ITS AUTHORIZED REPRESENTATIVES HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, OR (II) ANY CLAIM ATTRIBUTABLE TO ERRORS, OMMISIONS OR OTHER INACCURACIES IN THE SERVICE AND/OR MATERIALS OR INFORMATION DOWNLOADED THROUGH THE SERVICE.

			BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU. IN SUCH STATES OR JURISDICTIONS, LIABILITY IS LIMITED TO THE GREATEST EXTENT PERMITTED BY LAW, RESULTING IN THE SMALLEST AMOUNT, IN WHATEVER CURRENCY, PERMITTED FOR THE AGGREGATE LIABILITY FOR BOTH Simplifie Haystack INC., Simplifie Haystack Tech, Simplifie Haystack Career AND AFFILIATED PARTIES FOR A CLAIM DERIVED FROM OR RELATED TO OUR WEBSITE OR THE Simplifie Haystack Platform. THIS IS IN PLACE OF ANY AND ALL OTHER REMEDIES OTHERWISE AVAILABLE.

			<strong>Miscellaneous Provisions</strong>
			This End User License Agreement is be governed by and construed in accordance with the laws of the Philippines, without giving effect to any applicable conflict of laws provisions. If for any reason a court of competent jurisdiction finds any provision or portion of this End User License Agreement to be unenforceable, the remainder of the agreement will continue in full force and effect.

			The Terms of Use and this End User License Agreement constitutes the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. Any waiver of any provision of the Terms of Use and this End User License Agreement will be effective only if in writing and signed by Simplifie Haystack Career.

			The End User License Agreement can be changed by Simplifie Haystack Career at any time. Simplifie Haystack Career cannot be held liable for any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from changes to the EULA.

			<strong>Acceptance</strong>
			BY SIGNING UP FOR AN ACCOUNT, YOU ARE STATING THAT YOU ARE OF LEGAL AGE AND HAVE READ, UNDERSTOOD AND AGREE TO BE BOUND BY THIS END USER LICENSE AGREEMENT.
		</div>
	</div>
</div>