CREATE TABLE ads(id INT NOT NULL AUTO_INCREMENT,
script VARCHAR(255) NOT NULL,
script_type VARCHAR(255) NOT NULL,
description TEXT NOT NULL,
width INT NOT NULL,
height INT NOT NULL,
image VARCHAR(255) NOT NULL,
date_from DATETIME NOT NULL,
date_to DATETIME NOT NULL,
enabled TINYINT(1) NOT NULL,
owner_full_name VARCHAR(255) NOT NULL,
owner_email VARCHAR(255) NOT NULL,
owner_landline VARCHAR(255) NOT NULL,
owner_mobile VARCHAR(255) NOT NULL,
company_name VARCHAR(255) NOT NULL,
company_address VARCHAR(255) NOT NULL,
company_city VARCHAR(255) NOT NULL,
company_country VARCHAR(255) NOT NULL,
company_zip_code VARCHAR(255) NOT NULL,
company_landline VARCHAR(255) NOT NULL,
company_mobile VARCHAR(255) NOT NULL,
payable_amount FLOAT(11) NOT NULL,
paid_amount FLOAT(11) NOT NULL,
paid_by VARCHAR(255) NOT NULL,
created_on DATETIME NOT NULL,
last_updated DATETIME NOT NULL,
paid_on DATETIME NOT NULL,
PRIMARY KEY (id))