CREATE TABLE blogs(id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(255) NOT NULL,
content VARCHAR(255) NOT NULL,
slug VARCHAR(255) NOT NULL,
publish_state VARCHAR(255) NOT NULL,
tags VARCHAR(255) NOT NULL,
PRIMARY KEY (id))