CREATE TABLE educations(id INT NOT NULL AUTO_INCREMENT,
resume_id INT NOT NULL,
degree VARCHAR(255) NOT NULL,
field_of_study VARCHAR(255) NOT NULL,
school VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL,
city VARCHAR(255) NOT NULL,
PRIMARY KEY (id))